#pragma once

#define NameOfGame u8"–«¬∂π»ŒÔ”Ô"

//∑÷±Ê¬ 
#define DESIGN_RESOLUTION_WIDTH 1280
#define DESIGN_RESOLUTION_HEIGHT 720
#define SMALL_RESOLUTION_WIDTH 480
#define SMALL_RESOLUTION_HIGHT 320
#define NEDIUM_RESOLUTION_WIDTH 1024
#define NEDIUM_RESOLUTION_HEIGHT 768
#define LARGE_RESOLUTION_WIDTH 2048
#define LARGE_RESOLUTION_HEIGHT 1536


