#pragma once

#define NameOfGame u8"星露谷物语"

//分辨率
#define DESIGN_RESOLUTION_WIDTH 1280
#define DESIGN_RESOLUTION_HEIGHT 720
#define SMALL_RESOLUTION_WIDTH 480
#define SMALL_RESOLUTION_HIGHT 320
#define NEDIUM_RESOLUTION_WIDTH 1024
#define NEDIUM_RESOLUTION_HEIGHT 768
#define LARGE_RESOLUTION_WIDTH 2048
#define LARGE_RESOLUTION_HEIGHT 1536

//字体
#define TEXT_SIZE 30
#define COLOR_RED 0
#define COLOR_GREEN 32
#define COLOR_BLUE 96
#define ALPHA 255


